project:
  type: website
  output-dir: docs

website:
  search: true
  navbar:
    right:
      - icon: github
        href: https://github.com/jmanuelascacibar
      - icon: twitter
        href: https://twitter.com/jmascacibar
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
  page-footer: 
    center: "Copyright 2024, Jose Manuel Ascacibar" 
    border: true
    background: light
  google-analytics: "G-RSXXM1QQ7W"
  cookie-consent: 
    type: implied
    style: simple
    palette: light


  back-to-top-navigation: true
  

format:
  html:
    theme: sandstone
    css: styles.css


theme:
  light: flatly
  dark: darkly
