project:
  type: website
  output-dir: docs

website:
  search: true
  navbar:
    right:
      - icon: github
        href: https://github.com/jmanuelascacibar
      - icon: twitter
        href: https://twitter.com/jmascacibar
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
  page-footer: 
    center: "Copyright 2024, Jose Manuel Ascaibar" 
    border: true
    background: light


  back-to-top-navigation: true
  

format:
  html:
    theme: sandstone
    css: styles.css



