<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="JM Ascacibar">
<meta name="dcterms.date" content="2024-05-17">

<title>Working with Chunks in Pandas, PyArrow, and Parquet - Amex Competition example</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jmanuelascacibar"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/jmascacibar"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Working with Chunks in Pandas, PyArrow, and Parquet - Amex Competition example</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Pandas</div>
                <div class="quarto-category">PyArrow</div>
                <div class="quarto-category">Parquet</div>
                <div class="quarto-category">Amex</div>
                <div class="quarto-category">data transformation</div>
                <div class="quarto-category">data types</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>JM Ascacibar </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 17, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="4">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction---the-amex-default-prediction-competition" id="toc-introduction---the-amex-default-prediction-competition" class="nav-link active" data-scroll-target="#introduction---the-amex-default-prediction-competition">Introduction - The AMEX Default Prediction Competition</a></li>
  <li><a href="#you-dont-need-to-load-the-data-all-at-once" id="toc-you-dont-need-to-load-the-data-all-at-once" class="nav-link" data-scroll-target="#you-dont-need-to-load-the-data-all-at-once">You don’t need to load the data all at once</a></li>
  <li><a href="#data-preprocessing" id="toc-data-preprocessing" class="nav-link" data-scroll-target="#data-preprocessing">Data preprocessing</a>
  <ul class="collapse">
  <li><a href="#customer_id-hurts-your-eyes" id="toc-customer_id-hurts-your-eyes" class="nav-link" data-scroll-target="#customer_id-hurts-your-eyes"><code>customer_ID</code> hurts your eyes!</a></li>
  <li><a href="#from-11-categorical-columns-to-13-categorical-columns" id="toc-from-11-categorical-columns-to-13-categorical-columns" class="nav-link" data-scroll-target="#from-11-categorical-columns-to-13-categorical-columns">From 11 categorical columns to 13 categorical columns</a></li>
  <li><a href="#convert-s_2-to-a-datetime-data-type" id="toc-convert-s_2-to-a-datetime-data-type" class="nav-link" data-scroll-target="#convert-s_2-to-a-datetime-data-type">Convert <code>S_2</code> to a <code>datetime</code> data type</a></li>
  <li><a href="#columns-float64-to-float32-or-float16" id="toc-columns-float64-to-float32-or-float16" class="nav-link" data-scroll-target="#columns-float64-to-float32-or-float16">185 columns <code>float64</code> to <code>float32</code> or <code>float16</code></a></li>
  </ul></li>
  <li><a href="#chunk-strategy" id="toc-chunk-strategy" class="nav-link" data-scroll-target="#chunk-strategy">Chunk strategy</a></li>
  <li><a href="#introduction-to-pyarrow-and-parquet" id="toc-introduction-to-pyarrow-and-parquet" class="nav-link" data-scroll-target="#introduction-to-pyarrow-and-parquet">Introduction to PyArrow and Parquet</a></li>
  <li><a href="#running-the-whole-code" id="toc-running-the-whole-code" class="nav-link" data-scroll-target="#running-the-whole-code">Running the whole code</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><em>Chunks in Pandas, PyArrow, and Parquet - Amex Competition</em></p>
<p><img src="dalle.jpg" class="img-fluid"></p>
<div id="cell-2" class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> psutil</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> gc</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyarrow.parquet <span class="im">as</span> pq</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyarrow <span class="im">as</span> pa</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>pd.options.display.max_columns <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>pd.options.display.max_rows <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>pd.options.display.max_info_columns <span class="op">=</span> <span class="dv">300</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-3" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> available_memory_gb():</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> psutil.virtual_memory().available <span class="op">/</span> (<span class="dv">1024</span><span class="op">**</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction---the-amex-default-prediction-competition" class="level2">
<h2 class="anchored" data-anchor-id="introduction---the-amex-default-prediction-competition">Introduction - The AMEX Default Prediction Competition</h2>
<p>The AMEX default prediction competition in Kaggle is a binary classification problem where the goal is to predict whether a credit card holder will default on their payment within 120 days after the latest credit card statement based on data from a 18-month performance window after the latest credit card statement.</p>
<p>The first step in any data science project is to load the data and understand its structure. The problem here is that the dataset is 50GB in size and it is not possible to load it all into memory at once (at least not in my machine). So here is where headaches start to appear.</p>
<p>In this notebook, I will show how to load the data in chunks using Pandas and PyArrow, and how to save it in Parquet format. This way, we can load the data in chunks and avoid memory issues.</p>
</section>
<section id="you-dont-need-to-load-the-data-all-at-once" class="level2">
<h2 class="anchored" data-anchor-id="you-dont-need-to-load-the-data-all-at-once">You don’t need to load the data all at once</h2>
<p>The first thing to understand is that you don’t need to load the data all at once. You can have a first glance to the data by loading only a small sample of it. This will give you an idea of the data structure and help you to decide what to do next.</p>
<div id="cell-6" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>PATH <span class="op">=</span> <span class="st">'/home/jmanu/git/amex_competition/train_data.csv'</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(PATH, nrows<span class="op">=</span><span class="dv">35000</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>data.head(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">customer_ID</th>
<th data-quarto-table-cell-role="th">S_2</th>
<th data-quarto-table-cell-role="th">P_2</th>
<th data-quarto-table-cell-role="th">D_39</th>
<th data-quarto-table-cell-role="th">B_1</th>
<th data-quarto-table-cell-role="th">B_2</th>
<th data-quarto-table-cell-role="th">R_1</th>
<th data-quarto-table-cell-role="th">S_3</th>
<th data-quarto-table-cell-role="th">D_41</th>
<th data-quarto-table-cell-role="th">B_3</th>
<th data-quarto-table-cell-role="th">D_42</th>
<th data-quarto-table-cell-role="th">D_43</th>
<th data-quarto-table-cell-role="th">D_44</th>
<th data-quarto-table-cell-role="th">B_4</th>
<th data-quarto-table-cell-role="th">D_45</th>
<th data-quarto-table-cell-role="th">B_5</th>
<th data-quarto-table-cell-role="th">R_2</th>
<th data-quarto-table-cell-role="th">D_46</th>
<th data-quarto-table-cell-role="th">D_47</th>
<th data-quarto-table-cell-role="th">D_48</th>
<th data-quarto-table-cell-role="th">D_49</th>
<th data-quarto-table-cell-role="th">B_6</th>
<th data-quarto-table-cell-role="th">B_7</th>
<th data-quarto-table-cell-role="th">B_8</th>
<th data-quarto-table-cell-role="th">D_50</th>
<th data-quarto-table-cell-role="th">D_51</th>
<th data-quarto-table-cell-role="th">B_9</th>
<th data-quarto-table-cell-role="th">R_3</th>
<th data-quarto-table-cell-role="th">D_52</th>
<th data-quarto-table-cell-role="th">P_3</th>
<th data-quarto-table-cell-role="th">B_10</th>
<th data-quarto-table-cell-role="th">D_53</th>
<th data-quarto-table-cell-role="th">S_5</th>
<th data-quarto-table-cell-role="th">B_11</th>
<th data-quarto-table-cell-role="th">S_6</th>
<th data-quarto-table-cell-role="th">D_54</th>
<th data-quarto-table-cell-role="th">R_4</th>
<th data-quarto-table-cell-role="th">S_7</th>
<th data-quarto-table-cell-role="th">B_12</th>
<th data-quarto-table-cell-role="th">S_8</th>
<th data-quarto-table-cell-role="th">D_55</th>
<th data-quarto-table-cell-role="th">D_56</th>
<th data-quarto-table-cell-role="th">B_13</th>
<th data-quarto-table-cell-role="th">R_5</th>
<th data-quarto-table-cell-role="th">D_58</th>
<th data-quarto-table-cell-role="th">S_9</th>
<th data-quarto-table-cell-role="th">B_14</th>
<th data-quarto-table-cell-role="th">D_59</th>
<th data-quarto-table-cell-role="th">D_60</th>
<th data-quarto-table-cell-role="th">D_61</th>
<th data-quarto-table-cell-role="th">B_15</th>
<th data-quarto-table-cell-role="th">S_11</th>
<th data-quarto-table-cell-role="th">D_62</th>
<th data-quarto-table-cell-role="th">D_63</th>
<th data-quarto-table-cell-role="th">D_64</th>
<th data-quarto-table-cell-role="th">D_65</th>
<th data-quarto-table-cell-role="th">B_16</th>
<th data-quarto-table-cell-role="th">B_17</th>
<th data-quarto-table-cell-role="th">B_18</th>
<th data-quarto-table-cell-role="th">B_19</th>
<th data-quarto-table-cell-role="th">D_66</th>
<th data-quarto-table-cell-role="th">B_20</th>
<th data-quarto-table-cell-role="th">D_68</th>
<th data-quarto-table-cell-role="th">S_12</th>
<th data-quarto-table-cell-role="th">R_6</th>
<th data-quarto-table-cell-role="th">S_13</th>
<th data-quarto-table-cell-role="th">B_21</th>
<th data-quarto-table-cell-role="th">D_69</th>
<th data-quarto-table-cell-role="th">B_22</th>
<th data-quarto-table-cell-role="th">D_70</th>
<th data-quarto-table-cell-role="th">D_71</th>
<th data-quarto-table-cell-role="th">D_72</th>
<th data-quarto-table-cell-role="th">S_15</th>
<th data-quarto-table-cell-role="th">B_23</th>
<th data-quarto-table-cell-role="th">D_73</th>
<th data-quarto-table-cell-role="th">P_4</th>
<th data-quarto-table-cell-role="th">D_74</th>
<th data-quarto-table-cell-role="th">D_75</th>
<th data-quarto-table-cell-role="th">D_76</th>
<th data-quarto-table-cell-role="th">B_24</th>
<th data-quarto-table-cell-role="th">R_7</th>
<th data-quarto-table-cell-role="th">D_77</th>
<th data-quarto-table-cell-role="th">B_25</th>
<th data-quarto-table-cell-role="th">B_26</th>
<th data-quarto-table-cell-role="th">D_78</th>
<th data-quarto-table-cell-role="th">D_79</th>
<th data-quarto-table-cell-role="th">R_8</th>
<th data-quarto-table-cell-role="th">R_9</th>
<th data-quarto-table-cell-role="th">S_16</th>
<th data-quarto-table-cell-role="th">D_80</th>
<th data-quarto-table-cell-role="th">R_10</th>
<th data-quarto-table-cell-role="th">R_11</th>
<th data-quarto-table-cell-role="th">B_27</th>
<th data-quarto-table-cell-role="th">D_81</th>
<th data-quarto-table-cell-role="th">D_82</th>
<th data-quarto-table-cell-role="th">S_17</th>
<th data-quarto-table-cell-role="th">R_12</th>
<th data-quarto-table-cell-role="th">B_28</th>
<th data-quarto-table-cell-role="th">R_13</th>
<th data-quarto-table-cell-role="th">D_83</th>
<th data-quarto-table-cell-role="th">R_14</th>
<th data-quarto-table-cell-role="th">R_15</th>
<th data-quarto-table-cell-role="th">D_84</th>
<th data-quarto-table-cell-role="th">R_16</th>
<th data-quarto-table-cell-role="th">B_29</th>
<th data-quarto-table-cell-role="th">B_30</th>
<th data-quarto-table-cell-role="th">S_18</th>
<th data-quarto-table-cell-role="th">D_86</th>
<th data-quarto-table-cell-role="th">D_87</th>
<th data-quarto-table-cell-role="th">R_17</th>
<th data-quarto-table-cell-role="th">R_18</th>
<th data-quarto-table-cell-role="th">D_88</th>
<th data-quarto-table-cell-role="th">B_31</th>
<th data-quarto-table-cell-role="th">S_19</th>
<th data-quarto-table-cell-role="th">R_19</th>
<th data-quarto-table-cell-role="th">B_32</th>
<th data-quarto-table-cell-role="th">S_20</th>
<th data-quarto-table-cell-role="th">R_20</th>
<th data-quarto-table-cell-role="th">R_21</th>
<th data-quarto-table-cell-role="th">B_33</th>
<th data-quarto-table-cell-role="th">D_89</th>
<th data-quarto-table-cell-role="th">R_22</th>
<th data-quarto-table-cell-role="th">R_23</th>
<th data-quarto-table-cell-role="th">D_91</th>
<th data-quarto-table-cell-role="th">D_92</th>
<th data-quarto-table-cell-role="th">D_93</th>
<th data-quarto-table-cell-role="th">D_94</th>
<th data-quarto-table-cell-role="th">R_24</th>
<th data-quarto-table-cell-role="th">R_25</th>
<th data-quarto-table-cell-role="th">D_96</th>
<th data-quarto-table-cell-role="th">S_22</th>
<th data-quarto-table-cell-role="th">S_23</th>
<th data-quarto-table-cell-role="th">S_24</th>
<th data-quarto-table-cell-role="th">S_25</th>
<th data-quarto-table-cell-role="th">S_26</th>
<th data-quarto-table-cell-role="th">D_102</th>
<th data-quarto-table-cell-role="th">D_103</th>
<th data-quarto-table-cell-role="th">D_104</th>
<th data-quarto-table-cell-role="th">D_105</th>
<th data-quarto-table-cell-role="th">D_106</th>
<th data-quarto-table-cell-role="th">D_107</th>
<th data-quarto-table-cell-role="th">B_36</th>
<th data-quarto-table-cell-role="th">B_37</th>
<th data-quarto-table-cell-role="th">R_26</th>
<th data-quarto-table-cell-role="th">R_27</th>
<th data-quarto-table-cell-role="th">B_38</th>
<th data-quarto-table-cell-role="th">D_108</th>
<th data-quarto-table-cell-role="th">D_109</th>
<th data-quarto-table-cell-role="th">D_110</th>
<th data-quarto-table-cell-role="th">D_111</th>
<th data-quarto-table-cell-role="th">B_39</th>
<th data-quarto-table-cell-role="th">D_112</th>
<th data-quarto-table-cell-role="th">B_40</th>
<th data-quarto-table-cell-role="th">S_27</th>
<th data-quarto-table-cell-role="th">D_113</th>
<th data-quarto-table-cell-role="th">D_114</th>
<th data-quarto-table-cell-role="th">D_115</th>
<th data-quarto-table-cell-role="th">D_116</th>
<th data-quarto-table-cell-role="th">D_117</th>
<th data-quarto-table-cell-role="th">D_118</th>
<th data-quarto-table-cell-role="th">D_119</th>
<th data-quarto-table-cell-role="th">D_120</th>
<th data-quarto-table-cell-role="th">D_121</th>
<th data-quarto-table-cell-role="th">D_122</th>
<th data-quarto-table-cell-role="th">D_123</th>
<th data-quarto-table-cell-role="th">D_124</th>
<th data-quarto-table-cell-role="th">D_125</th>
<th data-quarto-table-cell-role="th">D_126</th>
<th data-quarto-table-cell-role="th">D_127</th>
<th data-quarto-table-cell-role="th">D_128</th>
<th data-quarto-table-cell-role="th">D_129</th>
<th data-quarto-table-cell-role="th">B_41</th>
<th data-quarto-table-cell-role="th">B_42</th>
<th data-quarto-table-cell-role="th">D_130</th>
<th data-quarto-table-cell-role="th">D_131</th>
<th data-quarto-table-cell-role="th">D_132</th>
<th data-quarto-table-cell-role="th">D_133</th>
<th data-quarto-table-cell-role="th">R_28</th>
<th data-quarto-table-cell-role="th">D_134</th>
<th data-quarto-table-cell-role="th">D_135</th>
<th data-quarto-table-cell-role="th">D_136</th>
<th data-quarto-table-cell-role="th">D_137</th>
<th data-quarto-table-cell-role="th">D_138</th>
<th data-quarto-table-cell-role="th">D_139</th>
<th data-quarto-table-cell-role="th">D_140</th>
<th data-quarto-table-cell-role="th">D_141</th>
<th data-quarto-table-cell-role="th">D_142</th>
<th data-quarto-table-cell-role="th">D_143</th>
<th data-quarto-table-cell-role="th">D_144</th>
<th data-quarto-table-cell-role="th">D_145</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...</td>
<td>2017-03-09</td>
<td>0.938469</td>
<td>0.001733</td>
<td>0.008724</td>
<td>1.006838</td>
<td>0.009228</td>
<td>0.124035</td>
<td>0.008771</td>
<td>0.004709</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000630</td>
<td>0.080986</td>
<td>0.708906</td>
<td>0.170600</td>
<td>0.006204</td>
<td>0.358587</td>
<td>0.525351</td>
<td>0.255736</td>
<td>NaN</td>
<td>0.063902</td>
<td>0.059416</td>
<td>0.006466</td>
<td>0.148698</td>
<td>1.335856</td>
<td>0.008207</td>
<td>0.001423</td>
<td>0.207334</td>
<td>0.736463</td>
<td>0.096219</td>
<td>NaN</td>
<td>0.023381</td>
<td>0.002768</td>
<td>0.008322</td>
<td>1.001519</td>
<td>0.008298</td>
<td>0.161345</td>
<td>0.148266</td>
<td>0.922998</td>
<td>0.354596</td>
<td>0.152025</td>
<td>0.118075</td>
<td>0.001882</td>
<td>0.158612</td>
<td>0.065728</td>
<td>0.018385</td>
<td>0.063646</td>
<td>0.199617</td>
<td>0.308233</td>
<td>0.016361</td>
<td>0.401619</td>
<td>0.091071</td>
<td>CR</td>
<td>O</td>
<td>0.007126</td>
<td>0.007665</td>
<td>NaN</td>
<td>0.652984</td>
<td>0.008520</td>
<td>NaN</td>
<td>0.004730</td>
<td>6.0</td>
<td>0.272008</td>
<td>0.008363</td>
<td>0.515222</td>
<td>0.002644</td>
<td>0.009013</td>
<td>0.004808</td>
<td>0.008342</td>
<td>0.119403</td>
<td>0.004802</td>
<td>0.108271</td>
<td>0.050882</td>
<td>NaN</td>
<td>0.007554</td>
<td>0.080422</td>
<td>0.069067</td>
<td>NaN</td>
<td>0.004327</td>
<td>0.007562</td>
<td>NaN</td>
<td>0.007729</td>
<td>0.000272</td>
<td>0.001576</td>
<td>0.004239</td>
<td>0.001434</td>
<td>NaN</td>
<td>0.002271</td>
<td>0.004061</td>
<td>0.007121</td>
<td>0.002456</td>
<td>0.002310</td>
<td>0.003532</td>
<td>0.506612</td>
<td>0.008033</td>
<td>1.009825</td>
<td>0.084683</td>
<td>0.003820</td>
<td>0.007043</td>
<td>0.000438</td>
<td>0.006452</td>
<td>0.000830</td>
<td>0.005055</td>
<td>NaN</td>
<td>0.0</td>
<td>0.005720</td>
<td>0.007084</td>
<td>NaN</td>
<td>0.000198</td>
<td>0.008907</td>
<td>NaN</td>
<td>1</td>
<td>0.002537</td>
<td>0.005177</td>
<td>0.006626</td>
<td>0.009705</td>
<td>0.007782</td>
<td>0.002450</td>
<td>1.001101</td>
<td>0.002665</td>
<td>0.007479</td>
<td>0.006893</td>
<td>1.503673</td>
<td>1.006133</td>
<td>0.003569</td>
<td>0.008871</td>
<td>0.003950</td>
<td>0.003647</td>
<td>0.004950</td>
<td>0.894090</td>
<td>0.135561</td>
<td>0.911191</td>
<td>0.974539</td>
<td>0.001243</td>
<td>0.766688</td>
<td>1.008691</td>
<td>1.004587</td>
<td>0.893734</td>
<td>NaN</td>
<td>0.670041</td>
<td>0.009968</td>
<td>0.004572</td>
<td>NaN</td>
<td>1.008949</td>
<td>2.0</td>
<td>NaN</td>
<td>0.004326</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.007336</td>
<td>0.210060</td>
<td>0.676922</td>
<td>0.007871</td>
<td>1.0</td>
<td>0.238250</td>
<td>0.0</td>
<td>4.0</td>
<td>0.232120</td>
<td>0.236266</td>
<td>0.0</td>
<td>0.702280</td>
<td>0.434345</td>
<td>0.003057</td>
<td>0.686516</td>
<td>0.008740</td>
<td>1.0</td>
<td>1.003319</td>
<td>1.007819</td>
<td>1.000080</td>
<td>0.006805</td>
<td>NaN</td>
<td>0.002052</td>
<td>0.005972</td>
<td>NaN</td>
<td>0.004345</td>
<td>0.001535</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.002427</td>
<td>0.003706</td>
<td>0.003818</td>
<td>NaN</td>
<td>0.000569</td>
<td>0.000610</td>
<td>0.002674</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...</td>
<td>2017-04-07</td>
<td>0.936665</td>
<td>0.005775</td>
<td>0.004923</td>
<td>1.000653</td>
<td>0.006151</td>
<td>0.126750</td>
<td>0.000798</td>
<td>0.002714</td>
<td>NaN</td>
<td>NaN</td>
<td>0.002526</td>
<td>0.069419</td>
<td>0.712795</td>
<td>0.113239</td>
<td>0.006206</td>
<td>0.353630</td>
<td>0.521311</td>
<td>0.223329</td>
<td>NaN</td>
<td>0.065261</td>
<td>0.057744</td>
<td>0.001614</td>
<td>0.149723</td>
<td>1.339794</td>
<td>0.008373</td>
<td>0.001984</td>
<td>0.202778</td>
<td>0.720886</td>
<td>0.099804</td>
<td>NaN</td>
<td>0.030599</td>
<td>0.002749</td>
<td>0.002482</td>
<td>1.009033</td>
<td>0.005136</td>
<td>0.140951</td>
<td>0.143530</td>
<td>0.919414</td>
<td>0.326757</td>
<td>0.156201</td>
<td>0.118737</td>
<td>0.001610</td>
<td>0.148459</td>
<td>0.093935</td>
<td>0.013035</td>
<td>0.065501</td>
<td>0.151387</td>
<td>0.265026</td>
<td>0.017688</td>
<td>0.406326</td>
<td>0.086805</td>
<td>CR</td>
<td>O</td>
<td>0.002413</td>
<td>0.007148</td>
<td>NaN</td>
<td>0.647093</td>
<td>0.002238</td>
<td>NaN</td>
<td>0.003879</td>
<td>6.0</td>
<td>0.188970</td>
<td>0.004030</td>
<td>0.509048</td>
<td>0.004193</td>
<td>0.007842</td>
<td>0.001283</td>
<td>0.006524</td>
<td>0.140611</td>
<td>0.000094</td>
<td>0.101018</td>
<td>0.040469</td>
<td>NaN</td>
<td>0.004832</td>
<td>0.081413</td>
<td>0.074166</td>
<td>NaN</td>
<td>0.004203</td>
<td>0.005304</td>
<td>NaN</td>
<td>0.001864</td>
<td>0.000979</td>
<td>0.009896</td>
<td>0.007597</td>
<td>0.000509</td>
<td>NaN</td>
<td>0.009810</td>
<td>0.000127</td>
<td>0.005966</td>
<td>0.000395</td>
<td>0.001327</td>
<td>0.007773</td>
<td>0.500855</td>
<td>0.000760</td>
<td>1.009461</td>
<td>0.081843</td>
<td>0.000347</td>
<td>0.007789</td>
<td>0.004311</td>
<td>0.002332</td>
<td>0.009469</td>
<td>0.003753</td>
<td>NaN</td>
<td>0.0</td>
<td>0.007584</td>
<td>0.006677</td>
<td>NaN</td>
<td>0.001142</td>
<td>0.005907</td>
<td>NaN</td>
<td>1</td>
<td>0.008427</td>
<td>0.008979</td>
<td>0.001854</td>
<td>0.009924</td>
<td>0.005987</td>
<td>0.002247</td>
<td>1.006779</td>
<td>0.002508</td>
<td>0.006827</td>
<td>0.002837</td>
<td>1.503577</td>
<td>1.005791</td>
<td>0.000571</td>
<td>0.000391</td>
<td>0.008351</td>
<td>0.008850</td>
<td>0.003180</td>
<td>0.902135</td>
<td>0.136333</td>
<td>0.919876</td>
<td>0.975624</td>
<td>0.004561</td>
<td>0.786007</td>
<td>1.000084</td>
<td>1.004118</td>
<td>0.906841</td>
<td>NaN</td>
<td>0.668647</td>
<td>0.003921</td>
<td>0.004654</td>
<td>NaN</td>
<td>1.003205</td>
<td>2.0</td>
<td>NaN</td>
<td>0.008707</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.007653</td>
<td>0.184093</td>
<td>0.822281</td>
<td>0.003444</td>
<td>1.0</td>
<td>0.247217</td>
<td>0.0</td>
<td>4.0</td>
<td>0.243532</td>
<td>0.241885</td>
<td>0.0</td>
<td>0.707017</td>
<td>0.430501</td>
<td>0.001306</td>
<td>0.686414</td>
<td>0.000755</td>
<td>1.0</td>
<td>1.008394</td>
<td>1.004333</td>
<td>1.008344</td>
<td>0.004407</td>
<td>NaN</td>
<td>0.001034</td>
<td>0.004838</td>
<td>NaN</td>
<td>0.007495</td>
<td>0.004931</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.003954</td>
<td>0.003167</td>
<td>0.005032</td>
<td>NaN</td>
<td>0.009576</td>
<td>0.005492</td>
<td>0.009217</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...</td>
<td>2017-05-28</td>
<td>0.954180</td>
<td>0.091505</td>
<td>0.021655</td>
<td>1.009672</td>
<td>0.006815</td>
<td>0.123977</td>
<td>0.007598</td>
<td>0.009423</td>
<td>NaN</td>
<td>NaN</td>
<td>0.007605</td>
<td>0.068839</td>
<td>0.720884</td>
<td>0.060492</td>
<td>0.003259</td>
<td>0.334650</td>
<td>0.524568</td>
<td>0.189424</td>
<td>NaN</td>
<td>0.066982</td>
<td>0.056647</td>
<td>0.005126</td>
<td>0.151955</td>
<td>1.337179</td>
<td>0.009355</td>
<td>0.007426</td>
<td>0.206629</td>
<td>0.738044</td>
<td>0.134073</td>
<td>NaN</td>
<td>0.048367</td>
<td>0.010077</td>
<td>0.000530</td>
<td>1.009184</td>
<td>0.006961</td>
<td>0.112229</td>
<td>0.137014</td>
<td>1.001977</td>
<td>0.304124</td>
<td>0.153795</td>
<td>0.114534</td>
<td>0.006328</td>
<td>0.139504</td>
<td>0.084757</td>
<td>0.056653</td>
<td>0.070607</td>
<td>0.305883</td>
<td>0.212165</td>
<td>0.063955</td>
<td>0.406768</td>
<td>0.094001</td>
<td>CR</td>
<td>O</td>
<td>0.001878</td>
<td>0.003636</td>
<td>NaN</td>
<td>0.645819</td>
<td>0.000408</td>
<td>NaN</td>
<td>0.004578</td>
<td>6.0</td>
<td>0.495308</td>
<td>0.006838</td>
<td>0.679257</td>
<td>0.001337</td>
<td>0.006025</td>
<td>0.009393</td>
<td>0.002615</td>
<td>0.075868</td>
<td>0.007152</td>
<td>0.103239</td>
<td>0.047454</td>
<td>NaN</td>
<td>0.006561</td>
<td>0.078891</td>
<td>0.076510</td>
<td>NaN</td>
<td>0.001782</td>
<td>0.001422</td>
<td>NaN</td>
<td>0.005419</td>
<td>0.006149</td>
<td>0.009629</td>
<td>0.003094</td>
<td>0.008295</td>
<td>NaN</td>
<td>0.009362</td>
<td>0.000954</td>
<td>0.005447</td>
<td>0.007345</td>
<td>0.007624</td>
<td>0.008811</td>
<td>0.504606</td>
<td>0.004056</td>
<td>1.004291</td>
<td>0.081954</td>
<td>0.002709</td>
<td>0.004093</td>
<td>0.007139</td>
<td>0.008358</td>
<td>0.002325</td>
<td>0.007381</td>
<td>NaN</td>
<td>0.0</td>
<td>0.005901</td>
<td>0.001185</td>
<td>NaN</td>
<td>0.008013</td>
<td>0.008882</td>
<td>NaN</td>
<td>1</td>
<td>0.007327</td>
<td>0.002016</td>
<td>0.008686</td>
<td>0.008446</td>
<td>0.007291</td>
<td>0.007794</td>
<td>1.001014</td>
<td>0.009634</td>
<td>0.009820</td>
<td>0.005080</td>
<td>1.503359</td>
<td>1.005801</td>
<td>0.007425</td>
<td>0.009234</td>
<td>0.002471</td>
<td>0.009769</td>
<td>0.005433</td>
<td>0.939654</td>
<td>0.134938</td>
<td>0.958699</td>
<td>0.974067</td>
<td>0.011736</td>
<td>0.806840</td>
<td>1.003014</td>
<td>1.009285</td>
<td>0.928719</td>
<td>NaN</td>
<td>0.670901</td>
<td>0.001264</td>
<td>0.019176</td>
<td>NaN</td>
<td>1.000754</td>
<td>2.0</td>
<td>NaN</td>
<td>0.004092</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.004312</td>
<td>0.154837</td>
<td>0.853498</td>
<td>0.003269</td>
<td>1.0</td>
<td>0.239867</td>
<td>0.0</td>
<td>4.0</td>
<td>0.240768</td>
<td>0.239710</td>
<td>0.0</td>
<td>0.704843</td>
<td>0.434409</td>
<td>0.003954</td>
<td>0.690101</td>
<td>0.009617</td>
<td>1.0</td>
<td>1.009307</td>
<td>1.007831</td>
<td>1.006878</td>
<td>0.003221</td>
<td>NaN</td>
<td>0.005681</td>
<td>0.005497</td>
<td>NaN</td>
<td>0.009227</td>
<td>0.009123</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.003269</td>
<td>0.007329</td>
<td>0.000427</td>
<td>NaN</td>
<td>0.003429</td>
<td>0.006986</td>
<td>0.002603</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...</td>
<td>2017-06-13</td>
<td>0.960384</td>
<td>0.002455</td>
<td>0.013683</td>
<td>1.002700</td>
<td>0.001373</td>
<td>0.117169</td>
<td>0.000685</td>
<td>0.005531</td>
<td>NaN</td>
<td>NaN</td>
<td>0.006406</td>
<td>0.055630</td>
<td>0.723997</td>
<td>0.166782</td>
<td>0.009918</td>
<td>0.323271</td>
<td>0.530929</td>
<td>0.135586</td>
<td>NaN</td>
<td>0.083720</td>
<td>0.049253</td>
<td>0.001418</td>
<td>0.151219</td>
<td>1.339909</td>
<td>0.006782</td>
<td>0.003515</td>
<td>0.208214</td>
<td>0.741813</td>
<td>0.134437</td>
<td>NaN</td>
<td>0.030063</td>
<td>0.009667</td>
<td>0.000783</td>
<td>1.007456</td>
<td>0.008706</td>
<td>0.102838</td>
<td>0.129017</td>
<td>0.704016</td>
<td>0.275055</td>
<td>0.155772</td>
<td>0.120740</td>
<td>0.004980</td>
<td>0.138100</td>
<td>0.048382</td>
<td>0.012498</td>
<td>0.065926</td>
<td>0.273553</td>
<td>0.204300</td>
<td>0.022732</td>
<td>0.405175</td>
<td>0.094854</td>
<td>CR</td>
<td>O</td>
<td>0.005899</td>
<td>0.005896</td>
<td>NaN</td>
<td>0.654358</td>
<td>0.005897</td>
<td>NaN</td>
<td>0.005207</td>
<td>6.0</td>
<td>0.508670</td>
<td>0.008183</td>
<td>0.515282</td>
<td>0.008716</td>
<td>0.005271</td>
<td>0.004554</td>
<td>0.002052</td>
<td>0.150209</td>
<td>0.005364</td>
<td>0.206394</td>
<td>0.031705</td>
<td>NaN</td>
<td>0.009559</td>
<td>0.077490</td>
<td>0.071547</td>
<td>NaN</td>
<td>0.005595</td>
<td>0.006363</td>
<td>NaN</td>
<td>0.000646</td>
<td>0.009193</td>
<td>0.008568</td>
<td>0.003895</td>
<td>0.005153</td>
<td>NaN</td>
<td>0.004876</td>
<td>0.005665</td>
<td>0.001888</td>
<td>0.004961</td>
<td>0.000034</td>
<td>0.004652</td>
<td>0.508998</td>
<td>0.006969</td>
<td>1.004728</td>
<td>0.060634</td>
<td>0.009982</td>
<td>0.008817</td>
<td>0.008690</td>
<td>0.007364</td>
<td>0.005924</td>
<td>0.008802</td>
<td>NaN</td>
<td>0.0</td>
<td>0.002520</td>
<td>0.003324</td>
<td>NaN</td>
<td>0.009455</td>
<td>0.008348</td>
<td>NaN</td>
<td>1</td>
<td>0.007053</td>
<td>0.003909</td>
<td>0.002478</td>
<td>0.006614</td>
<td>0.009977</td>
<td>0.007686</td>
<td>1.002775</td>
<td>0.007791</td>
<td>0.000458</td>
<td>0.007320</td>
<td>1.503701</td>
<td>1.007036</td>
<td>0.000664</td>
<td>0.003200</td>
<td>0.008507</td>
<td>0.004858</td>
<td>0.000063</td>
<td>0.913205</td>
<td>0.140058</td>
<td>0.926341</td>
<td>0.975499</td>
<td>0.007571</td>
<td>0.808214</td>
<td>1.001517</td>
<td>1.004514</td>
<td>0.935383</td>
<td>NaN</td>
<td>0.672620</td>
<td>0.002729</td>
<td>0.011720</td>
<td>NaN</td>
<td>1.005338</td>
<td>2.0</td>
<td>NaN</td>
<td>0.009703</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.002538</td>
<td>0.153939</td>
<td>0.844667</td>
<td>0.000053</td>
<td>1.0</td>
<td>0.240910</td>
<td>0.0</td>
<td>4.0</td>
<td>0.239400</td>
<td>0.240727</td>
<td>0.0</td>
<td>0.711546</td>
<td>0.436903</td>
<td>0.005135</td>
<td>0.687779</td>
<td>0.004649</td>
<td>1.0</td>
<td>1.001671</td>
<td>1.003460</td>
<td>1.007573</td>
<td>0.007703</td>
<td>NaN</td>
<td>0.007108</td>
<td>0.008261</td>
<td>NaN</td>
<td>0.007206</td>
<td>0.002409</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.006117</td>
<td>0.004516</td>
<td>0.003200</td>
<td>NaN</td>
<td>0.008419</td>
<td>0.006527</td>
<td>0.009600</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...</td>
<td>2017-07-16</td>
<td>0.947248</td>
<td>0.002483</td>
<td>0.015193</td>
<td>1.000727</td>
<td>0.007605</td>
<td>0.117325</td>
<td>0.004653</td>
<td>0.009312</td>
<td>NaN</td>
<td>NaN</td>
<td>0.007731</td>
<td>0.038862</td>
<td>0.720619</td>
<td>0.143630</td>
<td>0.006667</td>
<td>0.231009</td>
<td>0.529305</td>
<td>NaN</td>
<td>NaN</td>
<td>0.075900</td>
<td>0.048918</td>
<td>0.001199</td>
<td>0.154026</td>
<td>1.341735</td>
<td>0.000519</td>
<td>0.001362</td>
<td>0.205468</td>
<td>0.691986</td>
<td>0.121518</td>
<td>NaN</td>
<td>0.054221</td>
<td>0.009484</td>
<td>0.006698</td>
<td>1.003738</td>
<td>0.003846</td>
<td>0.094311</td>
<td>0.129539</td>
<td>0.917133</td>
<td>0.231110</td>
<td>0.154914</td>
<td>0.095178</td>
<td>0.001653</td>
<td>0.126443</td>
<td>0.039259</td>
<td>0.027897</td>
<td>0.063697</td>
<td>0.233103</td>
<td>0.175655</td>
<td>0.031171</td>
<td>0.487460</td>
<td>0.093915</td>
<td>CR</td>
<td>O</td>
<td>0.009479</td>
<td>0.001714</td>
<td>NaN</td>
<td>0.650112</td>
<td>0.007773</td>
<td>NaN</td>
<td>0.005851</td>
<td>6.0</td>
<td>0.216507</td>
<td>0.008605</td>
<td>0.507712</td>
<td>0.006821</td>
<td>0.000152</td>
<td>0.000104</td>
<td>0.001419</td>
<td>0.096441</td>
<td>0.007972</td>
<td>0.106020</td>
<td>0.032733</td>
<td>NaN</td>
<td>0.008156</td>
<td>0.076561</td>
<td>0.074432</td>
<td>NaN</td>
<td>0.004933</td>
<td>0.004831</td>
<td>NaN</td>
<td>0.001833</td>
<td>0.005738</td>
<td>0.003289</td>
<td>0.002608</td>
<td>0.007338</td>
<td>NaN</td>
<td>0.007447</td>
<td>0.004465</td>
<td>0.006111</td>
<td>0.002246</td>
<td>0.002109</td>
<td>0.001141</td>
<td>0.506213</td>
<td>0.001770</td>
<td>1.000904</td>
<td>0.062492</td>
<td>0.005860</td>
<td>0.001845</td>
<td>0.007816</td>
<td>0.002470</td>
<td>0.005516</td>
<td>0.007166</td>
<td>NaN</td>
<td>0.0</td>
<td>0.000155</td>
<td>0.001504</td>
<td>NaN</td>
<td>0.002019</td>
<td>0.002678</td>
<td>NaN</td>
<td>1</td>
<td>0.007728</td>
<td>0.003432</td>
<td>0.002199</td>
<td>0.005511</td>
<td>0.004105</td>
<td>0.009656</td>
<td>1.006536</td>
<td>0.005158</td>
<td>0.003341</td>
<td>0.000264</td>
<td>1.509905</td>
<td>1.002915</td>
<td>0.003079</td>
<td>0.003845</td>
<td>0.007190</td>
<td>0.002983</td>
<td>0.000535</td>
<td>0.921026</td>
<td>0.131620</td>
<td>0.933479</td>
<td>0.978027</td>
<td>0.018200</td>
<td>0.822281</td>
<td>1.006125</td>
<td>1.005735</td>
<td>0.953363</td>
<td>NaN</td>
<td>0.673869</td>
<td>0.009998</td>
<td>0.017598</td>
<td>NaN</td>
<td>1.003175</td>
<td>2.0</td>
<td>NaN</td>
<td>0.009120</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000130</td>
<td>0.120717</td>
<td>0.811199</td>
<td>0.008724</td>
<td>1.0</td>
<td>0.247939</td>
<td>0.0</td>
<td>4.0</td>
<td>0.244199</td>
<td>0.242325</td>
<td>0.0</td>
<td>0.705343</td>
<td>0.437433</td>
<td>0.002849</td>
<td>0.688774</td>
<td>0.000097</td>
<td>1.0</td>
<td>1.009886</td>
<td>1.005053</td>
<td>1.008132</td>
<td>0.009823</td>
<td>NaN</td>
<td>0.009680</td>
<td>0.004848</td>
<td>NaN</td>
<td>0.006312</td>
<td>0.004462</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.003671</td>
<td>0.004946</td>
<td>0.008889</td>
<td>NaN</td>
<td>0.001670</td>
<td>0.008126</td>
<td>0.009827</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>Using the <code>info()</code> method, you can have a better sense of how the dataset is structured.</p>
<div id="cell-8" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 190 columns):
 #    Column       Non-Null Count  Dtype  
---   ------       --------------  -----  
 0    customer_ID  35000 non-null  object 
 1    S_2          35000 non-null  object 
 2    P_2          34690 non-null  float64
 3    D_39         35000 non-null  float64
 4    B_1          35000 non-null  float64
 5    B_2          34994 non-null  float64
 6    R_1          35000 non-null  float64
 7    S_3          28053 non-null  float64
 8    D_41         34994 non-null  float64
 9    B_3          34994 non-null  float64
 10   D_42         4889 non-null   float64
 11   D_43         24217 non-null  float64
 12   D_44         33279 non-null  float64
 13   B_4          35000 non-null  float64
 14   D_45         34994 non-null  float64
 15   B_5          35000 non-null  float64
 16   R_2          35000 non-null  float64
 17   D_46         27411 non-null  float64
 18   D_47         35000 non-null  float64
 19   D_48         30448 non-null  float64
 20   D_49         3808 non-null   float64
 21   B_6          34999 non-null  float64
 22   B_7          35000 non-null  float64
 23   B_8          34833 non-null  float64
 24   D_50         15101 non-null  float64
 25   D_51         35000 non-null  float64
 26   B_9          35000 non-null  float64
 27   R_3          35000 non-null  float64
 28   D_52         34832 non-null  float64
 29   P_3          33203 non-null  float64
 30   B_10         35000 non-null  float64
 31   D_53         9055 non-null   float64
 32   S_5          35000 non-null  float64
 33   B_11         35000 non-null  float64
 34   S_6          35000 non-null  float64
 35   D_54         34994 non-null  float64
 36   R_4          35000 non-null  float64
 37   S_7          28053 non-null  float64
 38   B_12         35000 non-null  float64
 39   S_8          35000 non-null  float64
 40   D_55         33844 non-null  float64
 41   D_56         16107 non-null  float64
 42   B_13         34687 non-null  float64
 43   R_5          35000 non-null  float64
 44   D_58         35000 non-null  float64
 45   S_9          16298 non-null  float64
 46   B_14         35000 non-null  float64
 47   D_59         34374 non-null  float64
 48   D_60         35000 non-null  float64
 49   D_61         31232 non-null  float64
 50   B_15         34974 non-null  float64
 51   S_11         35000 non-null  float64
 52   D_62         30170 non-null  float64
 53   D_63         35000 non-null  object 
 54   D_64         33718 non-null  object 
 55   D_65         35000 non-null  float64
 56   B_16         34994 non-null  float64
 57   B_17         15208 non-null  float64
 58   B_18         35000 non-null  float64
 59   B_19         34994 non-null  float64
 60   D_66         3888 non-null   float64
 61   B_20         34994 non-null  float64
 62   D_68         33738 non-null  float64
 63   S_12         35000 non-null  float64
 64   R_6          35000 non-null  float64
 65   S_13         35000 non-null  float64
 66   B_21         35000 non-null  float64
 67   D_69         33846 non-null  float64
 68   B_22         34994 non-null  float64
 69   D_70         34440 non-null  float64
 70   D_71         35000 non-null  float64
 71   D_72         34866 non-null  float64
 72   S_15         35000 non-null  float64
 73   B_23         35000 non-null  float64
 74   D_73         362 non-null    float64
 75   P_4          35000 non-null  float64
 76   D_74         34901 non-null  float64
 77   D_75         35000 non-null  float64
 78   D_76         4140 non-null   float64
 79   B_24         35000 non-null  float64
 80   R_7          35000 non-null  float64
 81   D_77         18900 non-null  float64
 82   B_25         34974 non-null  float64
 83   B_26         34994 non-null  float64
 84   D_78         33279 non-null  float64
 85   D_79         34582 non-null  float64
 86   R_8          35000 non-null  float64
 87   R_9          2087 non-null   float64
 88   S_16         35000 non-null  float64
 89   D_80         34901 non-null  float64
 90   R_10         35000 non-null  float64
 91   R_11         35000 non-null  float64
 92   B_27         34994 non-null  float64
 93   D_81         34844 non-null  float64
 94   D_82         9126 non-null   float64
 95   S_17         35000 non-null  float64
 96   R_12         35000 non-null  float64
 97   B_28         35000 non-null  float64
 98   R_13         35000 non-null  float64
 99   D_83         33846 non-null  float64
 100  R_14         35000 non-null  float64
 101  R_15         35000 non-null  float64
 102  D_84         34832 non-null  float64
 103  R_16         35000 non-null  float64
 104  B_29         2401 non-null   float64
 105  B_30         34994 non-null  float64
 106  S_18         35000 non-null  float64
 107  D_86         35000 non-null  float64
 108  D_87         35 non-null     float64
 109  R_17         35000 non-null  float64
 110  R_18         35000 non-null  float64
 111  D_88         45 non-null     float64
 112  B_31         35000 non-null  int64  
 113  S_19         35000 non-null  float64
 114  R_19         35000 non-null  float64
 115  B_32         35000 non-null  float64
 116  S_20         35000 non-null  float64
 117  R_20         34999 non-null  float64
 118  R_21         35000 non-null  float64
 119  B_33         34994 non-null  float64
 120  D_89         34832 non-null  float64
 121  R_22         35000 non-null  float64
 122  R_23         35000 non-null  float64
 123  D_91         34066 non-null  float64
 124  D_92         35000 non-null  float64
 125  D_93         35000 non-null  float64
 126  D_94         35000 non-null  float64
 127  R_24         35000 non-null  float64
 128  R_25         35000 non-null  float64
 129  D_96         35000 non-null  float64
 130  S_22         34872 non-null  float64
 131  S_23         34998 non-null  float64
 132  S_24         34874 non-null  float64
 133  S_25         34917 non-null  float64
 134  S_26         34996 non-null  float64
 135  D_102        34751 non-null  float64
 136  D_103        34403 non-null  float64
 137  D_104        34403 non-null  float64
 138  D_105        15816 non-null  float64
 139  D_106        3771 non-null   float64
 140  D_107        34403 non-null  float64
 141  B_36         35000 non-null  float64
 142  B_37         35000 non-null  float64
 143  R_26         3717 non-null   float64
 144  R_27         34198 non-null  float64
 145  B_38         34994 non-null  float64
 146  D_108        202 non-null    float64
 147  D_109        34991 non-null  float64
 148  D_110        180 non-null    float64
 149  D_111        180 non-null    float64
 150  B_39         188 non-null    float64
 151  D_112        34990 non-null  float64
 152  B_40         35000 non-null  float64
 153  S_27         25742 non-null  float64
 154  D_113        33955 non-null  float64
 155  D_114        33955 non-null  float64
 156  D_115        33955 non-null  float64
 157  D_116        33955 non-null  float64
 158  D_117        33955 non-null  float64
 159  D_118        33955 non-null  float64
 160  D_119        33955 non-null  float64
 161  D_120        33955 non-null  float64
 162  D_121        33955 non-null  float64
 163  D_122        33955 non-null  float64
 164  D_123        33955 non-null  float64
 165  D_124        33955 non-null  float64
 166  D_125        33955 non-null  float64
 167  D_126        34310 non-null  float64
 168  D_127        35000 non-null  float64
 169  D_128        34403 non-null  float64
 170  D_129        34403 non-null  float64
 171  B_41         34996 non-null  float64
 172  B_42         498 non-null    float64
 173  D_130        34403 non-null  float64
 174  D_131        34403 non-null  float64
 175  D_132        3781 non-null   float64
 176  D_133        34739 non-null  float64
 177  R_28         35000 non-null  float64
 178  D_134        1317 non-null   float64
 179  D_135        1317 non-null   float64
 180  D_136        1317 non-null   float64
 181  D_137        1317 non-null   float64
 182  D_138        1317 non-null   float64
 183  D_139        34403 non-null  float64
 184  D_140        34751 non-null  float64
 185  D_141        34403 non-null  float64
 186  D_142        5945 non-null   float64
 187  D_143        34403 non-null  float64
 188  D_144        34751 non-null  float64
 189  D_145        34403 non-null  float64
dtypes: float64(185), int64(1), object(4)
memory usage: 50.7+ MB</code></pre>
</div>
</div>
<div id="cell-9" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Number of data types object cols: </span><span class="sc">{</span>data<span class="sc">.</span>select_dtypes(<span class="st">"object"</span>)<span class="sc">.</span>columns<span class="sc">.</span>size<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Number of data types int cols: </span><span class="sc">{</span>data<span class="sc">.</span>select_dtypes(<span class="st">"int64"</span>)<span class="sc">.</span>columns<span class="sc">.</span>size<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Number of data types float cols: </span><span class="sc">{</span>data<span class="sc">.</span>select_dtypes(<span class="st">"float64"</span>)<span class="sc">.</span>columns<span class="sc">.</span>size<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of data types object cols: 4
Number of data types int cols: 1
Number of data types float cols: 185</code></pre>
</div>
</div>
</section>
<section id="data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="data-preprocessing">Data preprocessing</h2>
<section id="customer_id-hurts-your-eyes" class="level3">
<h3 class="anchored" data-anchor-id="customer_id-hurts-your-eyes"><code>customer_ID</code> hurts your eyes!</h3>
<p>When you execute the head method in the dataframe, the <code>customer_ID</code> column hurts your eyes. It’s a column that store strings that appears to be a hexadecimal. This type of string typically represents binary data in a human-readable format, using the characters 0-9 and a-f (or A-F) to represent the values 0 through 15 in each digit. Given its length, it is likely that this column is a hash of some sort. Given its length (64 hexadecimal characters), this string is likely a SHA-256 hash.</p>
<p>This mean that each row uses 64 bytes of memory. So following Chris Deotte’s advice <a href="https://www.kaggle.com/competitions/amex-default-prediction/discussion/328054">here</a> and <a href="https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations/discussion/308635">here</a>, we are going to take the last 16 digits of the hexadecimal string and convert it to an integer.</p>
<div id="cell-11" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'customer_ID'</span>] <span class="op">=</span> data[<span class="st">'customer_ID'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">int</span>(x[<span class="op">-</span><span class="dv">16</span>:], <span class="dv">16</span>)).astype(<span class="st">'int32'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="from-11-categorical-columns-to-13-categorical-columns" class="level3">
<h3 class="anchored" data-anchor-id="from-11-categorical-columns-to-13-categorical-columns">From 11 categorical columns to 13 categorical columns</h3>
<p>American Express has also provide a list of categorical features that we can convert to categorical type in Pandas. This will reduce the memory usage of these columns. The list is below:</p>
<pre><code>['B_30', 'B_38', 'D_114', 'D_116', 'D_117', 'D_120', 'D_126', 'D_63', 'D_64', 'D_66', 'D_68']</code></pre>
<div id="cell-13" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cat_cols <span class="op">=</span> [<span class="st">'B_30'</span>, <span class="st">'B_38'</span>, <span class="st">'D_114'</span>, <span class="st">'D_116'</span>, <span class="st">'D_117'</span>, <span class="st">'D_120'</span>, <span class="st">'D_126'</span>, <span class="st">'D_63'</span>, <span class="st">'D_64'</span>, <span class="st">'D_66'</span>, <span class="st">'D_68'</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>data[cat_cols].head(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">B_30</th>
<th data-quarto-table-cell-role="th">B_38</th>
<th data-quarto-table-cell-role="th">D_114</th>
<th data-quarto-table-cell-role="th">D_116</th>
<th data-quarto-table-cell-role="th">D_117</th>
<th data-quarto-table-cell-role="th">D_120</th>
<th data-quarto-table-cell-role="th">D_126</th>
<th data-quarto-table-cell-role="th">D_63</th>
<th data-quarto-table-cell-role="th">D_64</th>
<th data-quarto-table-cell-role="th">D_66</th>
<th data-quarto-table-cell-role="th">D_68</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0</td>
<td>2.0</td>
<td>1.0</td>
<td>0.0</td>
<td>4.0</td>
<td>0.0</td>
<td>1.0</td>
<td>CR</td>
<td>O</td>
<td>NaN</td>
<td>6.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.0</td>
<td>2.0</td>
<td>1.0</td>
<td>0.0</td>
<td>4.0</td>
<td>0.0</td>
<td>1.0</td>
<td>CR</td>
<td>O</td>
<td>NaN</td>
<td>6.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0.0</td>
<td>2.0</td>
<td>1.0</td>
<td>0.0</td>
<td>4.0</td>
<td>0.0</td>
<td>1.0</td>
<td>CR</td>
<td>O</td>
<td>NaN</td>
<td>6.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0.0</td>
<td>2.0</td>
<td>1.0</td>
<td>0.0</td>
<td>4.0</td>
<td>0.0</td>
<td>1.0</td>
<td>CR</td>
<td>O</td>
<td>NaN</td>
<td>6.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.0</td>
<td>2.0</td>
<td>1.0</td>
<td>0.0</td>
<td>4.0</td>
<td>0.0</td>
<td>1.0</td>
<td>CR</td>
<td>O</td>
<td>NaN</td>
<td>6.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="cell-14" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data[cat_cols].nunique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>B_30     3
B_38     7
D_114    2
D_116    2
D_117    7
D_120    2
D_126    3
D_63     6
D_64     4
D_66     2
D_68     7
dtype: int64</code></pre>
</div>
</div>
<p>To convert a columns to categorical type, you can use the following code:</p>
<div id="cell-16" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data[cat_cols] <span class="op">=</span> data[cat_cols].astype(<span class="st">'category'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-17" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cat <span class="kw">in</span> cat_cols:</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    data[cat] <span class="op">=</span> data[cat].cat.codes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Among the numerical columns, we also discover that there are some columns that are categorical. We can convert them to categorical type in Pandas. This will reduce the memory usage of these columns</p>
<div id="cell-19" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> data.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>):</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> data[col].nunique() <span class="op">&lt;</span> <span class="dv">3</span>:</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">'Columns with less than 2 unique values'</span>, data[col].name, data[col].dtype)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Columns with less than 2 unique values D_87 float64
Columns with less than 2 unique values B_31 int64</code></pre>
</div>
</div>
<div id="cell-20" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data[[<span class="st">'D_87'</span>, <span class="st">'B_31'</span>]].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>D_87  B_31
1.0   1       29
      0        6
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-21" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> [<span class="st">'D_87'</span>, <span class="st">'B_31'</span>]:</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    data[col] <span class="op">=</span> data[col].fillna(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    data[col] <span class="op">=</span> data[col].astype(<span class="st">'int8'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="convert-s_2-to-a-datetime-data-type" class="level3">
<h3 class="anchored" data-anchor-id="convert-s_2-to-a-datetime-data-type">Convert <code>S_2</code> to a <code>datetime</code> data type</h3>
<p>The <code>S_2</code> column is a date column that is stored as a string. We can convert it to a datetime data type in Pandas using the following code:</p>
<div id="cell-23" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'S_2'</span>] <span class="op">=</span> pd.to_datetime(data[<span class="st">'S_2'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%Y-%m-</span><span class="sc">%d</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This will reduce the memory usage of this column but we can go further and split the date into year, month, and day columns. This will allow us to analyze the data by year, month, and day, and will also reduce the memory usage even further.</p>
<div id="cell-25" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split into separate columns</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'S_2_year'</span>] <span class="op">=</span> (data[<span class="st">'S_2'</span>].dt.year <span class="op">%</span> <span class="dv">100</span>).astype(<span class="st">'int8'</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'S_2_month'</span>] <span class="op">=</span> data[<span class="st">'S_2'</span>].dt.month.astype(<span class="st">'int8'</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'S_2_day'</span>] <span class="op">=</span> data[<span class="st">'S_2'</span>].dt.day.astype(<span class="st">'int8'</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="kw">del</span> data[<span class="st">'S_2'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="columns-float64-to-float32-or-float16" class="level3">
<h3 class="anchored" data-anchor-id="columns-float64-to-float32-or-float16">185 columns <code>float64</code> to <code>float32</code> or <code>float16</code></h3>
<p>The first thing you notice when you inspect the <code>info()</code> method is that we have 185 float64 columns which typically consume 64 bits, or 8 bytes per element. This type of data type is used to represent double precision floating point numbers, which are numbers that have very large or very small magnitude and/or require a significant number of digits of precision. As we are going to learn latter, we can reduce the memory usage by changing the data type of these columns to <code>float32</code> and even <code>float16</code>.</p>
<div id="cell-27" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(data.select_dtypes(include<span class="op">=</span>np.float64).columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>175</code></pre>
</div>
</div>
<p>After all the transformation so far, we reduced the number to 175 columns. If we change the data type of these columns to <code>float32</code>, we will reduce the memory usage by half. If we change the data type to <code>float16</code>, we will reduce the memory usage by 75%.</p>
<p>So converting from <code>float64</code> to <code>float32</code> you can save 50% of memory usage without a significant loss in precision for many applications.</p>
<p>As Chris Deotte pointed out in the notebook previously mentioned, They discovered that we can convert these to <code>float16</code> since the data has added uniform noise. This means that the data is not as precise as it seems. This can be also done for privacy protection.</p>
<div id="cell-29" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> data.select_dtypes(include<span class="op">=</span>np.float64).columns:</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    data[col] <span class="op">=</span> data[col].fillna(<span class="op">-</span><span class="dv">1</span>).astype(<span class="st">'float16'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="chunk-strategy" class="level2">
<h2 class="anchored" data-anchor-id="chunk-strategy">Chunk strategy</h2>
<p>Once we’ve thoroughly understood our dataset and identified all necessary transformations to make it more manageable, the next step is to apply these transformations to the entire dataset. To avoid memory issues, we will process the data in chunks, similar to how batches are used in deep learning. Therefore, it’s essential to develop a strategy for determining the sizes of these chunks. We will calculate the memory consumption per row based on our original sample data, allowing us to optimize the chunk size effectively.</p>
<p>Memory consumption for 35,000 rows: 59.81 MB</p>
<div id="cell-32" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(PATH, nrows<span class="op">=</span><span class="dv">35000</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>data.memory_usage(deep<span class="op">=</span><span class="va">True</span>).<span class="bu">sum</span>() <span class="op">/</span> <span class="dv">1024</span><span class="op">**</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<pre><code>59.81640434265137</code></pre>
</div>
</div>
<p>Memory usage per row is: <span class="math inline">\(\frac{59.81}{35000}=0.0017\)</span> MB</p>
<div id="cell-34" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>(data.memory_usage(deep<span class="op">=</span><span class="va">True</span>).<span class="bu">sum</span>() <span class="op">/</span> <span class="dv">1024</span><span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>data.shape[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<pre><code>0.0017090401240757534</code></pre>
</div>
</div>
<p>In order to have enough memory we are going to consider to use half of the memory available.</p>
<p>Target memory usage aprox: <span class="math inline">\(\frac{8.26}{2}=4.15\)</span> GB</p>
<div id="cell-36" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>available_memory_gb() <span class="op">/</span> <span class="dv">2</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<pre><code>4.147722244262695</code></pre>
</div>
</div>
<p>Chunk size in rows: <span class="math inline">\(\frac{4.15}{0.0017}=2431508\)</span> rows</p>
<div id="cell-38" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>(available_memory_gb() <span class="op">/</span> <span class="dv">2</span>) <span class="op">*</span><span class="dv">1000</span> <span class="op">/</span>  ((data.memory_usage(deep<span class="op">=</span><span class="va">True</span>).<span class="bu">sum</span>() <span class="op">/</span> <span class="dv">1024</span><span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>data.shape[<span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<pre><code>2431507.734935815</code></pre>
</div>
</div>
<p>A more conservative approach would be to scale down this estimate by a factor to ensure smooth processing.</p>
<div id="cell-40" class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fl">2431507.734935815</span> <span class="op">*</span> <span class="fl">0.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="52">
<pre><code>243150.7734935815</code></pre>
</div>
</div>
<p>Our final chunk size will be 243151 rows.</p>
<div id="cell-42" class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="kw">del</span> data</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>gc.collect()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="53">
<pre><code>1194</code></pre>
</div>
</div>
</section>
<section id="introduction-to-pyarrow-and-parquet" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-pyarrow-and-parquet">Introduction to PyArrow and Parquet</h2>
<p>PyArrow is a Python library that provides a bridge between Python and the Apache Arrow in-memory data format.</p>
<p>Apache Arrow is designed to improve the performance and efficiency of data by providing a standardized in-memory columnar data format that can be shared between different systems and languages. PyArrow includes support for reading and writing Parquet files.</p>
<p><code>import pyarrow.parquet as pq</code> -&gt; Imports the PyArrow library’s Parquet module, which provides tools for reading and writing Parquet files</p>
<p><code>import pyarrow as pa</code> -&gt; Imports the PyArrow library to access data structures like Tables, which are used to interface with Parquet files and other Arrow functionalities.</p>
<p>Once the libraries have been imported, we need to define the path where the Parquet file is located. Also we need to initialize the <code>writer</code>variable to <code>None</code> that will be used to create a ParquetWriter object, which will be used to write the data to the Parquet file.</p>
<div id="cell-45" class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>output_path <span class="op">=</span> <span class="st">'train.parquet'</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>writer <span class="op">=</span> <span class="va">None</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Based on our estimation of memory usage, we set the chunksize to 243151. This is going to control how much data is read into memory at once. We can then iterate over the chunks of the DataFrame and write them to the Parquet file.</p>
<p>Next we can start to apply all the transformations to the data.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>chunksize <span class="op">=</span> <span class="dv">243151</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> chunk <span class="kw">in</span> pd.read_csv(PATH, chunksize<span class="op">=</span>chunksize, engine<span class="op">=</span><span class="st">'c'</span>):</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Transforming customer_ID</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'customer_ID'</span>] <span class="op">=</span> chunk[<span class="st">'customer_ID'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">int</span>(x[<span class="op">-</span><span class="dv">16</span>:], <span class="dv">16</span>)).astype(<span class="st">'int32'</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Apply datetime transformations </span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'S_2'</span>] <span class="op">=</span> pd.to_datetime(chunk[<span class="st">'S_2'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%Y-%m-</span><span class="sc">%d</span><span class="st">'</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'year_last_2_digits'</span>] <span class="op">=</span> chunk[<span class="st">'S_2'</span>].dt.year <span class="op">%</span> <span class="dv">100</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'month'</span>] <span class="op">=</span> chunk[<span class="st">'S_2'</span>].dt.month</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'day'</span>] <span class="op">=</span> chunk[<span class="st">'S_2'</span>].dt.day</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    chunk[[<span class="st">'year_last_2_digits'</span>, <span class="st">'month'</span>, <span class="st">'day'</span>]] <span class="op">=</span> chunk[[<span class="st">'year_last_2_digits'</span>, <span class="st">'month'</span>, <span class="st">'day'</span>]].astype(<span class="st">'int8'</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Apply category transformations</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    chunk[cat_cols] <span class="op">=</span> chunk[cat_cols].astype(<span class="st">'category'</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> cat <span class="kw">in</span> cat_cols:</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>        chunk[cat] <span class="op">=</span> chunk[cat].cat.codes.astype(<span class="st">'int8'</span>)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Additional columns to convert to 'int8'</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> [<span class="st">'D_87'</span>, <span class="st">'B_31'</span>]:</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>        chunk[col] <span class="op">=</span> chunk[col].fillna(<span class="op">-</span><span class="dv">1</span>).astype(<span class="st">'int8'</span>)</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>     <span class="co"># Convert float64 columns to float16 for all floating type columns</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> chunk.select_dtypes(include<span class="op">=</span>np.float64).columns:</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>        chunk[col] <span class="op">=</span> chunk[col].fillna(<span class="op">-</span><span class="dv">1</span>).astype(<span class="st">'float16'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Inside of the loop, we need to convert the the <code>chunk</code> dataframe into a PyArrow Table object using the <code>pa.Table.from_pandas()</code> method. This method takes the DataFrame as input and returns a Table object that can be written to a Parquet file.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert DataFrame to PyArrow Table</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>table <span class="op">=</span> pa.Table.from_pandas(chunk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Now we need to initialize the ParquetWriter object if it is not already initialized. We can do this by checking if the <code>writer</code> variable is <code>None</code>. If it is, we create a new ParquetWriter object using the <code>pq.ParquetWriter()</code> method. This method takes the output path and the schema of the data as input.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> writer <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>        writer <span class="op">=</span> pq.ParquetWriter(output_path, table.schema, compression<span class="op">=</span><span class="st">'snappy'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Finally the next line of code, writes the PyArrow Table object to the Parquet file using the <code>writer.write_table()</code> method. This is done incrementally for each chunk of data read from the CSV file.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>writer.write_table(table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>After the loop is finished, we need to close the ParquetWriter object using the <code>writer.close()</code> method. This will finalize the writing process and save the data to the Parquet file.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> writer:</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    writer.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>This is a simple example of how to convert a large CSV file to a Parquet file using PyArrow. This process can be customized further based on the specific requirements of the data and the desired output format.</p>
</section>
<section id="running-the-whole-code" class="level2">
<h2 class="anchored" data-anchor-id="running-the-whole-code">Running the whole code</h2>
<p>Let’s run the whole code to get our final train set in Parquet format.</p>
<div id="cell-48" class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the path for the output Parquet file</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>output_path <span class="op">=</span> <span class="st">'train.parquet'</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize PyArrow Parquet writer, initially without a schema</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>writer <span class="op">=</span> <span class="va">None</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the CSV file in chunks</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>chunksize <span class="op">=</span> <span class="dv">243151</span>  <span class="co"># Customized to your available memory and dataset size</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Cat columns </span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>cat_cols <span class="op">=</span> [<span class="st">'B_30'</span>, <span class="st">'B_38'</span>, <span class="st">'D_114'</span>, <span class="st">'D_116'</span>, <span class="st">'D_117'</span>, <span class="st">'D_120'</span>, <span class="st">'D_126'</span>, <span class="st">'D_63'</span>, <span class="st">'D_64'</span>, <span class="st">'D_66'</span>, <span class="st">'D_68'</span>]</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> chunk <span class="kw">in</span> pd.read_csv(PATH, chunksize<span class="op">=</span>chunksize, na_values<span class="op">=-</span><span class="dv">1</span>, engine<span class="op">=</span><span class="st">'c'</span>):</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Transforming customer_ID</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'customer_ID'</span>] <span class="op">=</span> chunk[<span class="st">'customer_ID'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="bu">int</span>(x[<span class="op">-</span><span class="dv">16</span>:], <span class="dv">16</span>)).astype(<span class="st">'int32'</span>)</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Apply datetime transformations </span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'S_2'</span>] <span class="op">=</span> pd.to_datetime(chunk[<span class="st">'S_2'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%Y-%m-</span><span class="sc">%d</span><span class="st">'</span>)</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'year_last_2_digits'</span>] <span class="op">=</span> chunk[<span class="st">'S_2'</span>].dt.year <span class="op">%</span> <span class="dv">100</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'month'</span>] <span class="op">=</span> chunk[<span class="st">'S_2'</span>].dt.month</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>    chunk[<span class="st">'day'</span>] <span class="op">=</span> chunk[<span class="st">'S_2'</span>].dt.day</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>    chunk[[<span class="st">'year_last_2_digits'</span>, <span class="st">'month'</span>, <span class="st">'day'</span>]] <span class="op">=</span> chunk[[<span class="st">'year_last_2_digits'</span>, <span class="st">'month'</span>, <span class="st">'day'</span>]].astype(<span class="st">'int8'</span>)</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Apply category transformations</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>    chunk[cat_cols] <span class="op">=</span> chunk[cat_cols].astype(<span class="st">'category'</span>)</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> cat <span class="kw">in</span> cat_cols:</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>        chunk[cat] <span class="op">=</span> chunk[cat].cat.codes.astype(<span class="st">'int8'</span>)</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Additional columns to convert to 'int8'</span></span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> [<span class="st">'D_87'</span>, <span class="st">'B_31'</span>]:</span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>        chunk[col] <span class="op">=</span> chunk[col].fillna(<span class="op">-</span><span class="dv">1</span>).astype(<span class="st">'int8'</span>)</span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>     <span class="co"># Convert float64 columns to float16 for all floating type columns</span></span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> chunk.select_dtypes(include<span class="op">=</span>np.float64).columns:</span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>        chunk[col] <span class="op">=</span> chunk[col].fillna(<span class="op">-</span><span class="dv">1</span>).astype(<span class="st">'float16'</span>)</span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert DataFrame to PyArrow Table</span></span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a>    table <span class="op">=</span> pa.Table.from_pandas(chunk)</span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Initialize writer with schema from the first chunk</span></span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> writer <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb43-38"><a href="#cb43-38" aria-hidden="true" tabindex="-1"></a>        writer <span class="op">=</span> pq.ParquetWriter(output_path, table.schema, compression<span class="op">=</span><span class="st">'snappy'</span>)</span>
<span id="cb43-39"><a href="#cb43-39" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb43-40"><a href="#cb43-40" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Write table to Parquet file</span></span>
<span id="cb43-41"><a href="#cb43-41" aria-hidden="true" tabindex="-1"></a>    writer.write_table(table)</span>
<span id="cb43-42"><a href="#cb43-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-43"><a href="#cb43-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Don't forget to close the writer to finalize the Parquet file</span></span>
<span id="cb43-44"><a href="#cb43-44" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> writer:</span>
<span id="cb43-45"><a href="#cb43-45" aria-hidden="true" tabindex="-1"></a>    writer.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright 2024, Jose Manuel Ascaibar</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>